# -*- coding: utf-8 -*-
"""Python Tutorial

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GhdNF04hCh3Mhv6i8P4A5L7QoV5w7QPp

# **Python Tutorial**

Python is an easily-interpretable and versatile programming language that makes it popular for numerous applications such as data science & machine learning, web development, etc. 

*Note: This tutorial is exclusive to Python 3 only and not teach or include Python 2*

# Hello World 

The "Hello World" Statement is often the first program in learning a programming language; for Python, it can be implemented as shown below:
"""

print("Hello World!")

"""# Variables 

Variables can be used to store a specific, given value. An example of a variable can be depicted below:
"""

hello_world = "Hello World!"
print("Hello World!")

"""As you can see, we get the same output as the previously implemented "Hello World" statement without the use of a variable. In the above scenario, the value stored in the "hello_world" variable is printed. This act of assigning a value to a variable can be defined as "initializing" a variable, whereas simply typing the name of the variable itself is referred to as "declaring" a variable.

As such, there are several rules and guidelines in naming variables:
 1. Variable names can contain letters, numbers, and underscores only.
 2. Although variable names can be started with a letter or underscore, they cannot be started with a number.
 3. Spacing is not allowed.
 4. Variable names should be **concise** yet **precise**. For example, instead of using the variable name "this_is_the_name_of_bob", you can simply use "bob_name". 
 5. Keywords and names in python should not be used in variable names as they may result in confusion for the compiler. An example is naming a variable as "print" as it is used specifically to print values to the screen.

# Data Types

There exist many data types in Python which will be looked at below.

## Strings

A String is simply a series of character(s) and are marked by a set of quotes. Both single and double quotes can be used to define strings:
"""

"Hi! I am a String." # String with double quotes
'Hi! I am String as well.' # String with single quotes

"""There are many ways in which Strings can be used; these utilities or actions are referred to as "methods". Various methods exist for each data type in Python; however, some of the most prominent String methods in Python will be reviewed below, as well as ways in which String can be used:

  1. **Changing Case**: The case of words in a String can be changed by using either the upper() method, to make all letters in a String uppercase, or the lower() method, to make all letters in a String lowercase. Their implementation is shown below:
"""

s = "robert"
print(s.upper())
print(s.lower())

"""2. **Combining Strings:** The combining of String is also referred to as "String concatenation". The plus symbol ("+") is used to concatenate Strings. An example is shown here:"""

a = "is a great teacher."
b = "Mrs.Jones"
print (b +  " " + a) # Note that a String with just a single space will have to be added in between the variables b and a to allow for the space between the words "Jones" and "is"

"""3. **Escape Sequences:** Escape sequences, or nonprinting characters, can be used to create whitespace, such as newlines and tabs. To add a newline, we can simply use the "\n" escape sequence. To add a tab, we can simply use the "\t" escape sequence:"""

print("I love\nice cream!") # Implementation of the newline whitespace
print("I love\tice cream!") # Implementation of the tab whitespace

"""4. **Removing Whitespace:** Removing or "stripping" whitespace can cut excess whitespace in a String. This can be done using the "rstrip()" method to eliminate whitespace on the right side of the String, the "lstrip()" method to remove whitespace on the left side of the String, and the "strip()" method to remove whitespace from both sides of the String. The code implementation for these methods is shown below:"""

my_name = " Levi " 
print("Hello" + my_name + "Smith") 
print("Hello" + my_name.lstrip() + "Smith")
print("Hello" + my_name.rstrip() + "Smith")
print("Hello" + my_name.strip() + "Smith")

"""##Integers

Numbers can also be represented in seperate data types. The integer data type stores and manages integers. An example is shown below:
"""

n = 5

"""Several arithmetic operations can be performed on integers. They include:

1. **Addition:** Addition can be performed with the "+" symbol:
"""

a = 1 + 2
print(a)

"""2. **Subtraction:** Subtraction can be performed with the "-" symbol:"""

b = 3 - 1
print(b)

"""3. **Multiplication:** Multiplication can be performed with the "*" symbol:"""

c = 3 * 2
print(c)

"""4. **Division:** Division can be performed with the "/" symbol:"""

d = 10 / 4
print(d)

"""*Note that division with a single forward slash returns a float, a data type which is mentioned below. To perform integer division, we can replace the single forward slash "/" with a double slash "//".*

5. **Exponents:** Exponential operations can be performed with the "**" symbol, in which the number that precedes the symbol is the base and the number the follows the symbol is the exponent:
"""

e = 2 ** 3
print(e)

"""As such, all integer operations in Python follow the rules and sequence of the order of operations, as stated by the PEMDAS acronym. An example is shown here:"""

print((3 ** 2) - 6 / 2)

"""## Floats

Floats in Python are used to represent floating point numbers, which are numbers with a decimal point. An example is shown here:
"""

f = 3.14

"""The aforementioned arithmetic operations for integers also apply to floats.

## Booleans

Booleans in Python can be either "True" or "False". An example is shown here:
"""

z = True

"""## Casting Between Data Types

We can "cast" between data types in Python, meaning that we can convert between 2 discrete data types. An example for each of the 4 data types is shown here:
"""

print(float(-1)) # As you can see, the integer -1 is casted to an equivalent float -1
print(int(5.1)) # In this case, the float 1.1 is truncated, meaning that the decimal places of the float are ignored, while the rest of the float is cast to an integer
print(int(True)) # The boolean True is casted to 1 as an integer, and 1.0 as a float, whereas the boolean False is casted to 0 as an integer, and 0.0 as a float.
print(int('12')) # Strings can also be cast to integers if we have a String that contains a number in it.
print(str(True)) # Any data type can also be cast to a String using the str() method.

"""We can also determine the data type of a certain value passed as an argument to the type() function. Its usage for the previously implemented casting methods is shown below:"""

print(type(float(-1))) 
print(type(int(5.1))) 
print(type(int(True)))
print(type(int('12')))
print(type(str(True)))

"""# Lists

Lists are a crucial part of Python. They allow the collective storage of items of any data type. A list can be denoted by 2 square brackets "[]". Inside these square brackets are items, referred to as "elements", seperated by commas:
"""

one_to_five = [1, 2, 3, 4, 5] # Example of a list containing integers
basketball = ["I", "like", "basketball"] # Example of a list containing Strings
my_favorite_decimals = [3.14, 2,71] # Example of a list containing floats

"""Individual elements can be accessed in a list simply by the name of the list followed by the "index" of the desired element. An index is simply the position of a certain element in a list. It is important to note, however, that in Python (and in most other programming languages), the indexing of lists is zero-based, meaning that the first element has an index of 0, not 1, the second element has an index of 1, not 2, and so on. 

An example of accessing an element can be shown here:
"""

my_favorite_foods = ["ice cream", "pizza", "chocolate chip cookies"]
print(my_favorite_foods[2])
print(my_favorite_foods[2].upper()) # As each element in a list has its own data type, operations specific to that data type can be performed on a certain element in a list

"""An interesting aspect of accessing elements in Python is that indexes can be negative. For example, the index -1 returns the last element in a list.

It is important to note that lists are "dynamic" in Python, meaning that elements can be added, changed, inserted, or removed. Each of these three operations will be looked at below:

1. **Adding Elements:** When elements are added, or "appended" to the list, they are added to the end of the list. This can be done using the append() method:
"""

my_list = [4, 23, 3, 5, 65, 7, 22]
my_list.append(90)
print(my_list)

"""2. **Inserting Elements:** The insert() method can be used to insert elements into a list. To use this method, the index of the new element and the element to be added must be specified."""

shopping_list = ["tomatoes", "flour", "sugar", "eggs"]
shopping_list.insert(1, "milk")
print(shopping_list)

"""3. **Removing Elements:** The "del" statement can be used to remove an item of a specified index from a list. The del statement can be implemented as:"""

cars = ["honda", "toyota", "bmw", "acura", "lexus", "rolls-royce"]
del cars[4]
print(cars)

"""The value of an element in a list can be removed and then stored using the pop() method. The pop() method itself simply removes the last element in a list; however, an index can be specified in the method to remove an element from a certain position in the list:"""

random_numbers = [3.4, 32.3, 32, 6.8, 7.9, 5]
print(random_numbers.pop())
print(random_numbers.pop(0))

"""Elements can additionally be removed from a list based on their specific value using the "remove()" method. Note that, if there are 2 elements with the same value, the "remove()" method only removes the first occurence of the specified value."""

names = ["billy", "bob", "joe", "sai"]
names.remove("sai")
print(names)

"""4. **Sorting Lists:** Lists can also be sorted. The sort() method  sorts a list permanently. An example is shown here:"""

last_names = ['nemmani', 'chebrolu', 'bandi', 'yekollu']
last_names.sort()
print(last_names)

"""As you can see, the sort() method sorts a list of Strings in alphabetical order (note that all capital letters in a String take precedence over lowercase letters). Integers and floats, on the other hand, are simply sorted in ascending order from the left to the right.


Lists can also be sorted in a reverse order for each data type. This can be done via passing the "reverse=True" argument to the sort() method:
"""

alphabet = ['a', 'c', 'g', 'b', 'z', 'y']
alphabet.sort(reverse=True)
print(alphabet)

"""5. **Reversing Lists:** To reserve the order of a list (not sort it in a backwards order), we can use the "reverse()" method. An example of its implementation is shown below:"""

locations = ['australia', 'india', 'japan', 'china', 'italy']
locations.reverse()
print(locations)

"""6. **Finding the Length of a List:** To find the length of a list, the "len()" function can be used, in which the list is passed as an argument to the function and the length of the list is returned as an integer. It can be simply implemented as so:"""

trip_itinerary = ["taj mahal", "amber palace", "red fort", "golconda"]
print(len(trip_itinerary))

"""7. **Finding the Minimum and Maximum Value of a List:** Python conveniently provides us 2 functions to perform these operations - the "min()" function to find the least value of a list, and the "max()" function to find the greatest value of a list. An example of their usage is shown below:"""

a_list = [1, 5, 34, 6, 2, 543, 67544, -212, 8, -32]
print(max(a_list))
print(min(a_list))

"""# Loops

Loops allow a set of actions to be performed to every element in a list in an efficient manner. To loop through an entire list, we can use a "for" loop. Its implementation is shown below:
"""

scientists = ["einstein", "hawking", "newton", "feynman", "faraday"]
for scientist in scientists:
  print(scientist)

"""As you can see, the for loop "traverses" across each element of the list and stores this element in the variable "scientist". We can then print out all the elements in the "scientists" list.


However, simply printing each element is the only operation that can be performed inside a for-loop. Any operation relative to a data type can be performed for an element and can be placed inside a for-loop. An example of this is shown below:
"""

tests = ["sat", "act"]
for test in tests:
  print("I do not want to take the " + test.upper() + " this august.")

"""## Looping with Numbers

To generate a series of numbers, we can use the "range()" function. The range function simply returns an array containing a set of numbers between 2 numbers passed as arguments to the function. Its implementation is shown below with a for-loop:
"""

for number in range(0, 7):
  print(number)

"""As you can see, if we pass the integers m and n as arguments to the range() function as range(m, n), the function returns the range of values between m and n - 1. 

We can also use the range() function to return a set of numbers that are incremented by an integer more than one, meaning that they can skip numbers in a given range. We can do this simply by passing a third argument to the range() function, as shown in the code implementation below to print all odd numbers from 0 to 10:
"""

for odd_number in range(1, 10, 2):
  print(odd_number)

"""# Tuples

Tuples are expressed as comma seperated elements within parentheses. Elements in a tuple can be of any data type. An example of a tuple is shown below:
"""

a_tuple = ("heart", 4, 2.4323)
print(a_tuple)

"""The indexing of individual elements in tuples is the same as in lists in Python. Therefore, we can access individual elements the same way as we do in lists. An example is shown here:"""

another_tuple = ("ok", "bye", 32, 32.312)
print(another_tuple[1])